"""add_media_fields_and_relations

Revision ID: ab9e3cd2cf19
Revises: 35594e4da95c
Create Date: 2025-12-05 13:16:17.973859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9e3cd2cf19'
down_revision: Union[str, Sequence[str], None] = '35594e4da95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_relations',
    sa.Column('source_media_id', sa.Integer(), nullable=False),
    sa.Column('related_media_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['related_media_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['source_media_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('source_media_id', 'related_media_id')
    )
    op.add_column('anime', sa.Column('original_format', sa.String(length=50), nullable=True))
    op.add_column('anime', sa.Column('source_material', sa.String(length=200), nullable=True))
    op.add_column('anime', sa.Column('aired_from', sa.Date(), nullable=True))
    op.add_column('anime', sa.Column('aired_to', sa.Date(), nullable=True))
    op.add_column('anime', sa.Column('episodes', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('chapters', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('volumes', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('author', sa.String(length=200), nullable=True))
    op.add_column('anime', sa.Column('studio', sa.String(length=200), nullable=True))
    op.add_column('anime', sa.Column('serialization', sa.String(length=100), nullable=True))
    op.alter_column('anime', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('anime', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_column('anime', 'episodes_chapters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('episodes_chapters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('anime', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('anime', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('anime', 'serialization')
    op.drop_column('anime', 'studio')
    op.drop_column('anime', 'author')
    op.drop_column('anime', 'duration_minutes')
    op.drop_column('anime', 'volumes')
    op.drop_column('anime', 'chapters')
    op.drop_column('anime', 'episodes')
    op.drop_column('anime', 'aired_to')
    op.drop_column('anime', 'aired_from')
    op.drop_column('anime', 'source_material')
    op.drop_column('anime', 'original_format')
    op.drop_table('media_relations')
    # ### end Alembic commands ###
